FROM node:17-alpine

RUN npm install -g nodemon

WORKDIR /app

#Caching package json into working dir
COPY package.json .

RUN npm install

COPY . .

EXPOSE 4000
# required for docker desktop port mapping

CMD ["npm", "run", "dev"]


